// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aviato/plugin/v1/plugin.proto

package pluginv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pluginv1 "github.com/getaviato/aviato-go/pluginv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PluginServiceName is the fully-qualified name of the PluginService service.
	PluginServiceName = "aviato.plugin.v1.PluginService"
	// DataServiceName is the fully-qualified name of the DataService service.
	DataServiceName = "aviato.plugin.v1.DataService"
	// DatasourceServiceName is the fully-qualified name of the DatasourceService service.
	DatasourceServiceName = "aviato.plugin.v1.DatasourceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PluginServiceGetManifestProcedure is the fully-qualified name of the PluginService's GetManifest
	// RPC.
	PluginServiceGetManifestProcedure = "/aviato.plugin.v1.PluginService/GetManifest"
	// PluginServiceResolveFormProcedure is the fully-qualified name of the PluginService's ResolveForm
	// RPC.
	PluginServiceResolveFormProcedure = "/aviato.plugin.v1.PluginService/ResolveForm"
	// PluginServiceExecuteActionProcedure is the fully-qualified name of the PluginService's
	// ExecuteAction RPC.
	PluginServiceExecuteActionProcedure = "/aviato.plugin.v1.PluginService/ExecuteAction"
	// PluginServiceComputeFieldsProcedure is the fully-qualified name of the PluginService's
	// ComputeFields RPC.
	PluginServiceComputeFieldsProcedure = "/aviato.plugin.v1.PluginService/ComputeFields"
	// PluginServiceWriteFieldProcedure is the fully-qualified name of the PluginService's WriteField
	// RPC.
	PluginServiceWriteFieldProcedure = "/aviato.plugin.v1.PluginService/WriteField"
	// PluginServiceResolveSegmentProcedure is the fully-qualified name of the PluginService's
	// ResolveSegment RPC.
	PluginServiceResolveSegmentProcedure = "/aviato.plugin.v1.PluginService/ResolveSegment"
	// PluginServiceRunHookProcedure is the fully-qualified name of the PluginService's RunHook RPC.
	PluginServiceRunHookProcedure = "/aviato.plugin.v1.PluginService/RunHook"
	// PluginServiceSearchProcedure is the fully-qualified name of the PluginService's Search RPC.
	PluginServiceSearchProcedure = "/aviato.plugin.v1.PluginService/Search"
	// PluginServiceComputeChartProcedure is the fully-qualified name of the PluginService's
	// ComputeChart RPC.
	PluginServiceComputeChartProcedure = "/aviato.plugin.v1.PluginService/ComputeChart"
	// DataServiceListProcedure is the fully-qualified name of the DataService's List RPC.
	DataServiceListProcedure = "/aviato.plugin.v1.DataService/List"
	// DataServiceGetProcedure is the fully-qualified name of the DataService's Get RPC.
	DataServiceGetProcedure = "/aviato.plugin.v1.DataService/Get"
	// DataServiceCreateProcedure is the fully-qualified name of the DataService's Create RPC.
	DataServiceCreateProcedure = "/aviato.plugin.v1.DataService/Create"
	// DataServiceUpdateProcedure is the fully-qualified name of the DataService's Update RPC.
	DataServiceUpdateProcedure = "/aviato.plugin.v1.DataService/Update"
	// DataServiceDeleteProcedure is the fully-qualified name of the DataService's Delete RPC.
	DataServiceDeleteProcedure = "/aviato.plugin.v1.DataService/Delete"
	// DatasourceServiceDescribeCollectionsProcedure is the fully-qualified name of the
	// DatasourceService's DescribeCollections RPC.
	DatasourceServiceDescribeCollectionsProcedure = "/aviato.plugin.v1.DatasourceService/DescribeCollections"
	// DatasourceServiceListProcedure is the fully-qualified name of the DatasourceService's List RPC.
	DatasourceServiceListProcedure = "/aviato.plugin.v1.DatasourceService/List"
	// DatasourceServiceGetProcedure is the fully-qualified name of the DatasourceService's Get RPC.
	DatasourceServiceGetProcedure = "/aviato.plugin.v1.DatasourceService/Get"
	// DatasourceServiceCreateProcedure is the fully-qualified name of the DatasourceService's Create
	// RPC.
	DatasourceServiceCreateProcedure = "/aviato.plugin.v1.DatasourceService/Create"
	// DatasourceServiceUpdateProcedure is the fully-qualified name of the DatasourceService's Update
	// RPC.
	DatasourceServiceUpdateProcedure = "/aviato.plugin.v1.DatasourceService/Update"
	// DatasourceServiceDeleteProcedure is the fully-qualified name of the DatasourceService's Delete
	// RPC.
	DatasourceServiceDeleteProcedure = "/aviato.plugin.v1.DatasourceService/Delete"
	// DatasourceServiceListChangesProcedure is the fully-qualified name of the DatasourceService's
	// ListChanges RPC.
	DatasourceServiceListChangesProcedure = "/aviato.plugin.v1.DatasourceService/ListChanges"
)

// PluginServiceClient is a client for the aviato.plugin.v1.PluginService service.
type PluginServiceClient interface {
	// Declares what the plugin provides. Called at agent start and when the SDK reports a change.
	GetManifest(context.Context, *connect.Request[pluginv1.GetManifestRequest]) (*connect.Response[pluginv1.GetManifestResponse], error)
	// Resolves the dynamic parts of an action form (visibility, defaults, choices, …).
	ResolveForm(context.Context, *connect.Request[pluginv1.ResolveFormRequest]) (*connect.Response[pluginv1.ResolveFormResponse], error)
	ExecuteAction(context.Context, *connect.Request[pluginv1.ExecuteActionRequest]) (*connect.Response[pluginv1.ExecuteActionResponse], error)
	// Computes fields for a page of records at once.
	ComputeFields(context.Context, *connect.Request[pluginv1.ComputeFieldsRequest]) (*connect.Response[pluginv1.ComputeFieldsResponse], error)
	// Custom write behaviour for a field (for example splitting a full name).
	WriteField(context.Context, *connect.Request[pluginv1.WriteFieldRequest]) (*connect.Response[pluginv1.WriteFieldResponse], error)
	ResolveSegment(context.Context, *connect.Request[pluginv1.ResolveSegmentRequest]) (*connect.Response[pluginv1.ResolveSegmentResponse], error)
	RunHook(context.Context, *connect.Request[pluginv1.RunHookRequest]) (*connect.Response[pluginv1.RunHookResponse], error)
	Search(context.Context, *connect.Request[pluginv1.SearchRequest]) (*connect.Response[pluginv1.SearchResponse], error)
	ComputeChart(context.Context, *connect.Request[pluginv1.ComputeChartRequest]) (*connect.Response[pluginv1.ComputeChartResponse], error)
}

// NewPluginServiceClient constructs a client for the aviato.plugin.v1.PluginService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pluginServiceMethods := pluginv1.File_aviato_plugin_v1_plugin_proto.Services().ByName("PluginService").Methods()
	return &pluginServiceClient{
		getManifest: connect.NewClient[pluginv1.GetManifestRequest, pluginv1.GetManifestResponse](
			httpClient,
			baseURL+PluginServiceGetManifestProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("GetManifest")),
			connect.WithClientOptions(opts...),
		),
		resolveForm: connect.NewClient[pluginv1.ResolveFormRequest, pluginv1.ResolveFormResponse](
			httpClient,
			baseURL+PluginServiceResolveFormProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("ResolveForm")),
			connect.WithClientOptions(opts...),
		),
		executeAction: connect.NewClient[pluginv1.ExecuteActionRequest, pluginv1.ExecuteActionResponse](
			httpClient,
			baseURL+PluginServiceExecuteActionProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("ExecuteAction")),
			connect.WithClientOptions(opts...),
		),
		computeFields: connect.NewClient[pluginv1.ComputeFieldsRequest, pluginv1.ComputeFieldsResponse](
			httpClient,
			baseURL+PluginServiceComputeFieldsProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("ComputeFields")),
			connect.WithClientOptions(opts...),
		),
		writeField: connect.NewClient[pluginv1.WriteFieldRequest, pluginv1.WriteFieldResponse](
			httpClient,
			baseURL+PluginServiceWriteFieldProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("WriteField")),
			connect.WithClientOptions(opts...),
		),
		resolveSegment: connect.NewClient[pluginv1.ResolveSegmentRequest, pluginv1.ResolveSegmentResponse](
			httpClient,
			baseURL+PluginServiceResolveSegmentProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("ResolveSegment")),
			connect.WithClientOptions(opts...),
		),
		runHook: connect.NewClient[pluginv1.RunHookRequest, pluginv1.RunHookResponse](
			httpClient,
			baseURL+PluginServiceRunHookProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("RunHook")),
			connect.WithClientOptions(opts...),
		),
		search: connect.NewClient[pluginv1.SearchRequest, pluginv1.SearchResponse](
			httpClient,
			baseURL+PluginServiceSearchProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
		computeChart: connect.NewClient[pluginv1.ComputeChartRequest, pluginv1.ComputeChartResponse](
			httpClient,
			baseURL+PluginServiceComputeChartProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("ComputeChart")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginServiceClient implements PluginServiceClient.
type pluginServiceClient struct {
	getManifest    *connect.Client[pluginv1.GetManifestRequest, pluginv1.GetManifestResponse]
	resolveForm    *connect.Client[pluginv1.ResolveFormRequest, pluginv1.ResolveFormResponse]
	executeAction  *connect.Client[pluginv1.ExecuteActionRequest, pluginv1.ExecuteActionResponse]
	computeFields  *connect.Client[pluginv1.ComputeFieldsRequest, pluginv1.ComputeFieldsResponse]
	writeField     *connect.Client[pluginv1.WriteFieldRequest, pluginv1.WriteFieldResponse]
	resolveSegment *connect.Client[pluginv1.ResolveSegmentRequest, pluginv1.ResolveSegmentResponse]
	runHook        *connect.Client[pluginv1.RunHookRequest, pluginv1.RunHookResponse]
	search         *connect.Client[pluginv1.SearchRequest, pluginv1.SearchResponse]
	computeChart   *connect.Client[pluginv1.ComputeChartRequest, pluginv1.ComputeChartResponse]
}

// GetManifest calls aviato.plugin.v1.PluginService.GetManifest.
func (c *pluginServiceClient) GetManifest(ctx context.Context, req *connect.Request[pluginv1.GetManifestRequest]) (*connect.Response[pluginv1.GetManifestResponse], error) {
	return c.getManifest.CallUnary(ctx, req)
}

// ResolveForm calls aviato.plugin.v1.PluginService.ResolveForm.
func (c *pluginServiceClient) ResolveForm(ctx context.Context, req *connect.Request[pluginv1.ResolveFormRequest]) (*connect.Response[pluginv1.ResolveFormResponse], error) {
	return c.resolveForm.CallUnary(ctx, req)
}

// ExecuteAction calls aviato.plugin.v1.PluginService.ExecuteAction.
func (c *pluginServiceClient) ExecuteAction(ctx context.Context, req *connect.Request[pluginv1.ExecuteActionRequest]) (*connect.Response[pluginv1.ExecuteActionResponse], error) {
	return c.executeAction.CallUnary(ctx, req)
}

// ComputeFields calls aviato.plugin.v1.PluginService.ComputeFields.
func (c *pluginServiceClient) ComputeFields(ctx context.Context, req *connect.Request[pluginv1.ComputeFieldsRequest]) (*connect.Response[pluginv1.ComputeFieldsResponse], error) {
	return c.computeFields.CallUnary(ctx, req)
}

// WriteField calls aviato.plugin.v1.PluginService.WriteField.
func (c *pluginServiceClient) WriteField(ctx context.Context, req *connect.Request[pluginv1.WriteFieldRequest]) (*connect.Response[pluginv1.WriteFieldResponse], error) {
	return c.writeField.CallUnary(ctx, req)
}

// ResolveSegment calls aviato.plugin.v1.PluginService.ResolveSegment.
func (c *pluginServiceClient) ResolveSegment(ctx context.Context, req *connect.Request[pluginv1.ResolveSegmentRequest]) (*connect.Response[pluginv1.ResolveSegmentResponse], error) {
	return c.resolveSegment.CallUnary(ctx, req)
}

// RunHook calls aviato.plugin.v1.PluginService.RunHook.
func (c *pluginServiceClient) RunHook(ctx context.Context, req *connect.Request[pluginv1.RunHookRequest]) (*connect.Response[pluginv1.RunHookResponse], error) {
	return c.runHook.CallUnary(ctx, req)
}

// Search calls aviato.plugin.v1.PluginService.Search.
func (c *pluginServiceClient) Search(ctx context.Context, req *connect.Request[pluginv1.SearchRequest]) (*connect.Response[pluginv1.SearchResponse], error) {
	return c.search.CallUnary(ctx, req)
}

// ComputeChart calls aviato.plugin.v1.PluginService.ComputeChart.
func (c *pluginServiceClient) ComputeChart(ctx context.Context, req *connect.Request[pluginv1.ComputeChartRequest]) (*connect.Response[pluginv1.ComputeChartResponse], error) {
	return c.computeChart.CallUnary(ctx, req)
}

// PluginServiceHandler is an implementation of the aviato.plugin.v1.PluginService service.
type PluginServiceHandler interface {
	// Declares what the plugin provides. Called at agent start and when the SDK reports a change.
	GetManifest(context.Context, *connect.Request[pluginv1.GetManifestRequest]) (*connect.Response[pluginv1.GetManifestResponse], error)
	// Resolves the dynamic parts of an action form (visibility, defaults, choices, …).
	ResolveForm(context.Context, *connect.Request[pluginv1.ResolveFormRequest]) (*connect.Response[pluginv1.ResolveFormResponse], error)
	ExecuteAction(context.Context, *connect.Request[pluginv1.ExecuteActionRequest]) (*connect.Response[pluginv1.ExecuteActionResponse], error)
	// Computes fields for a page of records at once.
	ComputeFields(context.Context, *connect.Request[pluginv1.ComputeFieldsRequest]) (*connect.Response[pluginv1.ComputeFieldsResponse], error)
	// Custom write behaviour for a field (for example splitting a full name).
	WriteField(context.Context, *connect.Request[pluginv1.WriteFieldRequest]) (*connect.Response[pluginv1.WriteFieldResponse], error)
	ResolveSegment(context.Context, *connect.Request[pluginv1.ResolveSegmentRequest]) (*connect.Response[pluginv1.ResolveSegmentResponse], error)
	RunHook(context.Context, *connect.Request[pluginv1.RunHookRequest]) (*connect.Response[pluginv1.RunHookResponse], error)
	Search(context.Context, *connect.Request[pluginv1.SearchRequest]) (*connect.Response[pluginv1.SearchResponse], error)
	ComputeChart(context.Context, *connect.Request[pluginv1.ComputeChartRequest]) (*connect.Response[pluginv1.ComputeChartResponse], error)
}

// NewPluginServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginServiceHandler(svc PluginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginServiceMethods := pluginv1.File_aviato_plugin_v1_plugin_proto.Services().ByName("PluginService").Methods()
	pluginServiceGetManifestHandler := connect.NewUnaryHandler(
		PluginServiceGetManifestProcedure,
		svc.GetManifest,
		connect.WithSchema(pluginServiceMethods.ByName("GetManifest")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceResolveFormHandler := connect.NewUnaryHandler(
		PluginServiceResolveFormProcedure,
		svc.ResolveForm,
		connect.WithSchema(pluginServiceMethods.ByName("ResolveForm")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceExecuteActionHandler := connect.NewUnaryHandler(
		PluginServiceExecuteActionProcedure,
		svc.ExecuteAction,
		connect.WithSchema(pluginServiceMethods.ByName("ExecuteAction")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceComputeFieldsHandler := connect.NewUnaryHandler(
		PluginServiceComputeFieldsProcedure,
		svc.ComputeFields,
		connect.WithSchema(pluginServiceMethods.ByName("ComputeFields")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceWriteFieldHandler := connect.NewUnaryHandler(
		PluginServiceWriteFieldProcedure,
		svc.WriteField,
		connect.WithSchema(pluginServiceMethods.ByName("WriteField")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceResolveSegmentHandler := connect.NewUnaryHandler(
		PluginServiceResolveSegmentProcedure,
		svc.ResolveSegment,
		connect.WithSchema(pluginServiceMethods.ByName("ResolveSegment")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceRunHookHandler := connect.NewUnaryHandler(
		PluginServiceRunHookProcedure,
		svc.RunHook,
		connect.WithSchema(pluginServiceMethods.ByName("RunHook")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceSearchHandler := connect.NewUnaryHandler(
		PluginServiceSearchProcedure,
		svc.Search,
		connect.WithSchema(pluginServiceMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceComputeChartHandler := connect.NewUnaryHandler(
		PluginServiceComputeChartProcedure,
		svc.ComputeChart,
		connect.WithSchema(pluginServiceMethods.ByName("ComputeChart")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aviato.plugin.v1.PluginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginServiceGetManifestProcedure:
			pluginServiceGetManifestHandler.ServeHTTP(w, r)
		case PluginServiceResolveFormProcedure:
			pluginServiceResolveFormHandler.ServeHTTP(w, r)
		case PluginServiceExecuteActionProcedure:
			pluginServiceExecuteActionHandler.ServeHTTP(w, r)
		case PluginServiceComputeFieldsProcedure:
			pluginServiceComputeFieldsHandler.ServeHTTP(w, r)
		case PluginServiceWriteFieldProcedure:
			pluginServiceWriteFieldHandler.ServeHTTP(w, r)
		case PluginServiceResolveSegmentProcedure:
			pluginServiceResolveSegmentHandler.ServeHTTP(w, r)
		case PluginServiceRunHookProcedure:
			pluginServiceRunHookHandler.ServeHTTP(w, r)
		case PluginServiceSearchProcedure:
			pluginServiceSearchHandler.ServeHTTP(w, r)
		case PluginServiceComputeChartProcedure:
			pluginServiceComputeChartHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginServiceHandler struct{}

func (UnimplementedPluginServiceHandler) GetManifest(context.Context, *connect.Request[pluginv1.GetManifestRequest]) (*connect.Response[pluginv1.GetManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.PluginService.GetManifest is not implemented"))
}

func (UnimplementedPluginServiceHandler) ResolveForm(context.Context, *connect.Request[pluginv1.ResolveFormRequest]) (*connect.Response[pluginv1.ResolveFormResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.PluginService.ResolveForm is not implemented"))
}

func (UnimplementedPluginServiceHandler) ExecuteAction(context.Context, *connect.Request[pluginv1.ExecuteActionRequest]) (*connect.Response[pluginv1.ExecuteActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.PluginService.ExecuteAction is not implemented"))
}

func (UnimplementedPluginServiceHandler) ComputeFields(context.Context, *connect.Request[pluginv1.ComputeFieldsRequest]) (*connect.Response[pluginv1.ComputeFieldsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.PluginService.ComputeFields is not implemented"))
}

func (UnimplementedPluginServiceHandler) WriteField(context.Context, *connect.Request[pluginv1.WriteFieldRequest]) (*connect.Response[pluginv1.WriteFieldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.PluginService.WriteField is not implemented"))
}

func (UnimplementedPluginServiceHandler) ResolveSegment(context.Context, *connect.Request[pluginv1.ResolveSegmentRequest]) (*connect.Response[pluginv1.ResolveSegmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.PluginService.ResolveSegment is not implemented"))
}

func (UnimplementedPluginServiceHandler) RunHook(context.Context, *connect.Request[pluginv1.RunHookRequest]) (*connect.Response[pluginv1.RunHookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.PluginService.RunHook is not implemented"))
}

func (UnimplementedPluginServiceHandler) Search(context.Context, *connect.Request[pluginv1.SearchRequest]) (*connect.Response[pluginv1.SearchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.PluginService.Search is not implemented"))
}

func (UnimplementedPluginServiceHandler) ComputeChart(context.Context, *connect.Request[pluginv1.ComputeChartRequest]) (*connect.Response[pluginv1.ComputeChartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.PluginService.ComputeChart is not implemented"))
}

// DataServiceClient is a client for the aviato.plugin.v1.DataService service.
type DataServiceClient interface {
	List(context.Context, *connect.Request[pluginv1.ListRequest]) (*connect.Response[pluginv1.ListResponse], error)
	Get(context.Context, *connect.Request[pluginv1.GetRequest]) (*connect.Response[pluginv1.GetResponse], error)
	Create(context.Context, *connect.Request[pluginv1.CreateRequest]) (*connect.Response[pluginv1.CreateResponse], error)
	Update(context.Context, *connect.Request[pluginv1.UpdateRequest]) (*connect.Response[pluginv1.UpdateResponse], error)
	Delete(context.Context, *connect.Request[pluginv1.DeleteRequest]) (*connect.Response[pluginv1.DeleteResponse], error)
}

// NewDataServiceClient constructs a client for the aviato.plugin.v1.DataService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDataServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DataServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dataServiceMethods := pluginv1.File_aviato_plugin_v1_plugin_proto.Services().ByName("DataService").Methods()
	return &dataServiceClient{
		list: connect.NewClient[pluginv1.ListRequest, pluginv1.ListResponse](
			httpClient,
			baseURL+DataServiceListProcedure,
			connect.WithSchema(dataServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[pluginv1.GetRequest, pluginv1.GetResponse](
			httpClient,
			baseURL+DataServiceGetProcedure,
			connect.WithSchema(dataServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[pluginv1.CreateRequest, pluginv1.CreateResponse](
			httpClient,
			baseURL+DataServiceCreateProcedure,
			connect.WithSchema(dataServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[pluginv1.UpdateRequest, pluginv1.UpdateResponse](
			httpClient,
			baseURL+DataServiceUpdateProcedure,
			connect.WithSchema(dataServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[pluginv1.DeleteRequest, pluginv1.DeleteResponse](
			httpClient,
			baseURL+DataServiceDeleteProcedure,
			connect.WithSchema(dataServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dataServiceClient implements DataServiceClient.
type dataServiceClient struct {
	list   *connect.Client[pluginv1.ListRequest, pluginv1.ListResponse]
	get    *connect.Client[pluginv1.GetRequest, pluginv1.GetResponse]
	create *connect.Client[pluginv1.CreateRequest, pluginv1.CreateResponse]
	update *connect.Client[pluginv1.UpdateRequest, pluginv1.UpdateResponse]
	delete *connect.Client[pluginv1.DeleteRequest, pluginv1.DeleteResponse]
}

// List calls aviato.plugin.v1.DataService.List.
func (c *dataServiceClient) List(ctx context.Context, req *connect.Request[pluginv1.ListRequest]) (*connect.Response[pluginv1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Get calls aviato.plugin.v1.DataService.Get.
func (c *dataServiceClient) Get(ctx context.Context, req *connect.Request[pluginv1.GetRequest]) (*connect.Response[pluginv1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Create calls aviato.plugin.v1.DataService.Create.
func (c *dataServiceClient) Create(ctx context.Context, req *connect.Request[pluginv1.CreateRequest]) (*connect.Response[pluginv1.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls aviato.plugin.v1.DataService.Update.
func (c *dataServiceClient) Update(ctx context.Context, req *connect.Request[pluginv1.UpdateRequest]) (*connect.Response[pluginv1.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls aviato.plugin.v1.DataService.Delete.
func (c *dataServiceClient) Delete(ctx context.Context, req *connect.Request[pluginv1.DeleteRequest]) (*connect.Response[pluginv1.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// DataServiceHandler is an implementation of the aviato.plugin.v1.DataService service.
type DataServiceHandler interface {
	List(context.Context, *connect.Request[pluginv1.ListRequest]) (*connect.Response[pluginv1.ListResponse], error)
	Get(context.Context, *connect.Request[pluginv1.GetRequest]) (*connect.Response[pluginv1.GetResponse], error)
	Create(context.Context, *connect.Request[pluginv1.CreateRequest]) (*connect.Response[pluginv1.CreateResponse], error)
	Update(context.Context, *connect.Request[pluginv1.UpdateRequest]) (*connect.Response[pluginv1.UpdateResponse], error)
	Delete(context.Context, *connect.Request[pluginv1.DeleteRequest]) (*connect.Response[pluginv1.DeleteResponse], error)
}

// NewDataServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDataServiceHandler(svc DataServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dataServiceMethods := pluginv1.File_aviato_plugin_v1_plugin_proto.Services().ByName("DataService").Methods()
	dataServiceListHandler := connect.NewUnaryHandler(
		DataServiceListProcedure,
		svc.List,
		connect.WithSchema(dataServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	dataServiceGetHandler := connect.NewUnaryHandler(
		DataServiceGetProcedure,
		svc.Get,
		connect.WithSchema(dataServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	dataServiceCreateHandler := connect.NewUnaryHandler(
		DataServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(dataServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	dataServiceUpdateHandler := connect.NewUnaryHandler(
		DataServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(dataServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	dataServiceDeleteHandler := connect.NewUnaryHandler(
		DataServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(dataServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aviato.plugin.v1.DataService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DataServiceListProcedure:
			dataServiceListHandler.ServeHTTP(w, r)
		case DataServiceGetProcedure:
			dataServiceGetHandler.ServeHTTP(w, r)
		case DataServiceCreateProcedure:
			dataServiceCreateHandler.ServeHTTP(w, r)
		case DataServiceUpdateProcedure:
			dataServiceUpdateHandler.ServeHTTP(w, r)
		case DataServiceDeleteProcedure:
			dataServiceDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDataServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDataServiceHandler struct{}

func (UnimplementedDataServiceHandler) List(context.Context, *connect.Request[pluginv1.ListRequest]) (*connect.Response[pluginv1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DataService.List is not implemented"))
}

func (UnimplementedDataServiceHandler) Get(context.Context, *connect.Request[pluginv1.GetRequest]) (*connect.Response[pluginv1.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DataService.Get is not implemented"))
}

func (UnimplementedDataServiceHandler) Create(context.Context, *connect.Request[pluginv1.CreateRequest]) (*connect.Response[pluginv1.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DataService.Create is not implemented"))
}

func (UnimplementedDataServiceHandler) Update(context.Context, *connect.Request[pluginv1.UpdateRequest]) (*connect.Response[pluginv1.UpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DataService.Update is not implemented"))
}

func (UnimplementedDataServiceHandler) Delete(context.Context, *connect.Request[pluginv1.DeleteRequest]) (*connect.Response[pluginv1.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DataService.Delete is not implemented"))
}

// DatasourceServiceClient is a client for the aviato.plugin.v1.DatasourceService service.
type DatasourceServiceClient interface {
	// The custom collections, with their fields, keys, relations and capabilities.
	DescribeCollections(context.Context, *connect.Request[pluginv1.DescribeCollectionsRequest]) (*connect.Response[pluginv1.DescribeCollectionsResponse], error)
	List(context.Context, *connect.Request[pluginv1.DatasourceServiceListRequest]) (*connect.Response[pluginv1.DatasourceServiceListResponse], error)
	Get(context.Context, *connect.Request[pluginv1.DatasourceServiceGetRequest]) (*connect.Response[pluginv1.DatasourceServiceGetResponse], error)
	Create(context.Context, *connect.Request[pluginv1.DatasourceServiceCreateRequest]) (*connect.Response[pluginv1.DatasourceServiceCreateResponse], error)
	Update(context.Context, *connect.Request[pluginv1.DatasourceServiceUpdateRequest]) (*connect.Response[pluginv1.DatasourceServiceUpdateResponse], error)
	Delete(context.Context, *connect.Request[pluginv1.DatasourceServiceDeleteRequest]) (*connect.Response[pluginv1.DatasourceServiceDeleteResponse], error)
	// Replication strategy: records changed since a cursor, and deletions.
	ListChanges(context.Context, *connect.Request[pluginv1.ListChangesRequest]) (*connect.Response[pluginv1.ListChangesResponse], error)
}

// NewDatasourceServiceClient constructs a client for the aviato.plugin.v1.DatasourceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatasourceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatasourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	datasourceServiceMethods := pluginv1.File_aviato_plugin_v1_plugin_proto.Services().ByName("DatasourceService").Methods()
	return &datasourceServiceClient{
		describeCollections: connect.NewClient[pluginv1.DescribeCollectionsRequest, pluginv1.DescribeCollectionsResponse](
			httpClient,
			baseURL+DatasourceServiceDescribeCollectionsProcedure,
			connect.WithSchema(datasourceServiceMethods.ByName("DescribeCollections")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[pluginv1.DatasourceServiceListRequest, pluginv1.DatasourceServiceListResponse](
			httpClient,
			baseURL+DatasourceServiceListProcedure,
			connect.WithSchema(datasourceServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[pluginv1.DatasourceServiceGetRequest, pluginv1.DatasourceServiceGetResponse](
			httpClient,
			baseURL+DatasourceServiceGetProcedure,
			connect.WithSchema(datasourceServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[pluginv1.DatasourceServiceCreateRequest, pluginv1.DatasourceServiceCreateResponse](
			httpClient,
			baseURL+DatasourceServiceCreateProcedure,
			connect.WithSchema(datasourceServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[pluginv1.DatasourceServiceUpdateRequest, pluginv1.DatasourceServiceUpdateResponse](
			httpClient,
			baseURL+DatasourceServiceUpdateProcedure,
			connect.WithSchema(datasourceServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[pluginv1.DatasourceServiceDeleteRequest, pluginv1.DatasourceServiceDeleteResponse](
			httpClient,
			baseURL+DatasourceServiceDeleteProcedure,
			connect.WithSchema(datasourceServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		listChanges: connect.NewClient[pluginv1.ListChangesRequest, pluginv1.ListChangesResponse](
			httpClient,
			baseURL+DatasourceServiceListChangesProcedure,
			connect.WithSchema(datasourceServiceMethods.ByName("ListChanges")),
			connect.WithClientOptions(opts...),
		),
	}
}

// datasourceServiceClient implements DatasourceServiceClient.
type datasourceServiceClient struct {
	describeCollections *connect.Client[pluginv1.DescribeCollectionsRequest, pluginv1.DescribeCollectionsResponse]
	list                *connect.Client[pluginv1.DatasourceServiceListRequest, pluginv1.DatasourceServiceListResponse]
	get                 *connect.Client[pluginv1.DatasourceServiceGetRequest, pluginv1.DatasourceServiceGetResponse]
	create              *connect.Client[pluginv1.DatasourceServiceCreateRequest, pluginv1.DatasourceServiceCreateResponse]
	update              *connect.Client[pluginv1.DatasourceServiceUpdateRequest, pluginv1.DatasourceServiceUpdateResponse]
	delete              *connect.Client[pluginv1.DatasourceServiceDeleteRequest, pluginv1.DatasourceServiceDeleteResponse]
	listChanges         *connect.Client[pluginv1.ListChangesRequest, pluginv1.ListChangesResponse]
}

// DescribeCollections calls aviato.plugin.v1.DatasourceService.DescribeCollections.
func (c *datasourceServiceClient) DescribeCollections(ctx context.Context, req *connect.Request[pluginv1.DescribeCollectionsRequest]) (*connect.Response[pluginv1.DescribeCollectionsResponse], error) {
	return c.describeCollections.CallUnary(ctx, req)
}

// List calls aviato.plugin.v1.DatasourceService.List.
func (c *datasourceServiceClient) List(ctx context.Context, req *connect.Request[pluginv1.DatasourceServiceListRequest]) (*connect.Response[pluginv1.DatasourceServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Get calls aviato.plugin.v1.DatasourceService.Get.
func (c *datasourceServiceClient) Get(ctx context.Context, req *connect.Request[pluginv1.DatasourceServiceGetRequest]) (*connect.Response[pluginv1.DatasourceServiceGetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Create calls aviato.plugin.v1.DatasourceService.Create.
func (c *datasourceServiceClient) Create(ctx context.Context, req *connect.Request[pluginv1.DatasourceServiceCreateRequest]) (*connect.Response[pluginv1.DatasourceServiceCreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls aviato.plugin.v1.DatasourceService.Update.
func (c *datasourceServiceClient) Update(ctx context.Context, req *connect.Request[pluginv1.DatasourceServiceUpdateRequest]) (*connect.Response[pluginv1.DatasourceServiceUpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls aviato.plugin.v1.DatasourceService.Delete.
func (c *datasourceServiceClient) Delete(ctx context.Context, req *connect.Request[pluginv1.DatasourceServiceDeleteRequest]) (*connect.Response[pluginv1.DatasourceServiceDeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// ListChanges calls aviato.plugin.v1.DatasourceService.ListChanges.
func (c *datasourceServiceClient) ListChanges(ctx context.Context, req *connect.Request[pluginv1.ListChangesRequest]) (*connect.Response[pluginv1.ListChangesResponse], error) {
	return c.listChanges.CallUnary(ctx, req)
}

// DatasourceServiceHandler is an implementation of the aviato.plugin.v1.DatasourceService service.
type DatasourceServiceHandler interface {
	// The custom collections, with their fields, keys, relations and capabilities.
	DescribeCollections(context.Context, *connect.Request[pluginv1.DescribeCollectionsRequest]) (*connect.Response[pluginv1.DescribeCollectionsResponse], error)
	List(context.Context, *connect.Request[pluginv1.DatasourceServiceListRequest]) (*connect.Response[pluginv1.DatasourceServiceListResponse], error)
	Get(context.Context, *connect.Request[pluginv1.DatasourceServiceGetRequest]) (*connect.Response[pluginv1.DatasourceServiceGetResponse], error)
	Create(context.Context, *connect.Request[pluginv1.DatasourceServiceCreateRequest]) (*connect.Response[pluginv1.DatasourceServiceCreateResponse], error)
	Update(context.Context, *connect.Request[pluginv1.DatasourceServiceUpdateRequest]) (*connect.Response[pluginv1.DatasourceServiceUpdateResponse], error)
	Delete(context.Context, *connect.Request[pluginv1.DatasourceServiceDeleteRequest]) (*connect.Response[pluginv1.DatasourceServiceDeleteResponse], error)
	// Replication strategy: records changed since a cursor, and deletions.
	ListChanges(context.Context, *connect.Request[pluginv1.ListChangesRequest]) (*connect.Response[pluginv1.ListChangesResponse], error)
}

// NewDatasourceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatasourceServiceHandler(svc DatasourceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	datasourceServiceMethods := pluginv1.File_aviato_plugin_v1_plugin_proto.Services().ByName("DatasourceService").Methods()
	datasourceServiceDescribeCollectionsHandler := connect.NewUnaryHandler(
		DatasourceServiceDescribeCollectionsProcedure,
		svc.DescribeCollections,
		connect.WithSchema(datasourceServiceMethods.ByName("DescribeCollections")),
		connect.WithHandlerOptions(opts...),
	)
	datasourceServiceListHandler := connect.NewUnaryHandler(
		DatasourceServiceListProcedure,
		svc.List,
		connect.WithSchema(datasourceServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	datasourceServiceGetHandler := connect.NewUnaryHandler(
		DatasourceServiceGetProcedure,
		svc.Get,
		connect.WithSchema(datasourceServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	datasourceServiceCreateHandler := connect.NewUnaryHandler(
		DatasourceServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(datasourceServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	datasourceServiceUpdateHandler := connect.NewUnaryHandler(
		DatasourceServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(datasourceServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	datasourceServiceDeleteHandler := connect.NewUnaryHandler(
		DatasourceServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(datasourceServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	datasourceServiceListChangesHandler := connect.NewUnaryHandler(
		DatasourceServiceListChangesProcedure,
		svc.ListChanges,
		connect.WithSchema(datasourceServiceMethods.ByName("ListChanges")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aviato.plugin.v1.DatasourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatasourceServiceDescribeCollectionsProcedure:
			datasourceServiceDescribeCollectionsHandler.ServeHTTP(w, r)
		case DatasourceServiceListProcedure:
			datasourceServiceListHandler.ServeHTTP(w, r)
		case DatasourceServiceGetProcedure:
			datasourceServiceGetHandler.ServeHTTP(w, r)
		case DatasourceServiceCreateProcedure:
			datasourceServiceCreateHandler.ServeHTTP(w, r)
		case DatasourceServiceUpdateProcedure:
			datasourceServiceUpdateHandler.ServeHTTP(w, r)
		case DatasourceServiceDeleteProcedure:
			datasourceServiceDeleteHandler.ServeHTTP(w, r)
		case DatasourceServiceListChangesProcedure:
			datasourceServiceListChangesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatasourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatasourceServiceHandler struct{}

func (UnimplementedDatasourceServiceHandler) DescribeCollections(context.Context, *connect.Request[pluginv1.DescribeCollectionsRequest]) (*connect.Response[pluginv1.DescribeCollectionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DatasourceService.DescribeCollections is not implemented"))
}

func (UnimplementedDatasourceServiceHandler) List(context.Context, *connect.Request[pluginv1.DatasourceServiceListRequest]) (*connect.Response[pluginv1.DatasourceServiceListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DatasourceService.List is not implemented"))
}

func (UnimplementedDatasourceServiceHandler) Get(context.Context, *connect.Request[pluginv1.DatasourceServiceGetRequest]) (*connect.Response[pluginv1.DatasourceServiceGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DatasourceService.Get is not implemented"))
}

func (UnimplementedDatasourceServiceHandler) Create(context.Context, *connect.Request[pluginv1.DatasourceServiceCreateRequest]) (*connect.Response[pluginv1.DatasourceServiceCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DatasourceService.Create is not implemented"))
}

func (UnimplementedDatasourceServiceHandler) Update(context.Context, *connect.Request[pluginv1.DatasourceServiceUpdateRequest]) (*connect.Response[pluginv1.DatasourceServiceUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DatasourceService.Update is not implemented"))
}

func (UnimplementedDatasourceServiceHandler) Delete(context.Context, *connect.Request[pluginv1.DatasourceServiceDeleteRequest]) (*connect.Response[pluginv1.DatasourceServiceDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DatasourceService.Delete is not implemented"))
}

func (UnimplementedDatasourceServiceHandler) ListChanges(context.Context, *connect.Request[pluginv1.ListChangesRequest]) (*connect.Response[pluginv1.ListChangesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aviato.plugin.v1.DatasourceService.ListChanges is not implemented"))
}
